apiVersion: runtimes.management.ibm.com/v1
kind: Runtime
metadata:
  name: nginx-runtime
  namespace: kube-system
spec:
  displayName: Nginx Server
  description: High-performance HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server
  search:
    vm-based:
      label: app.management.ibm.com/nginx=true
    cluster-based:
      kind: daemonset
      label: app.kubernetes.io/name=nginx-ingress
  dynamicdetail:
    vm-based:
      columns: []
      applicationmgmt:
        resourceType: dummy
        join:
          host: dummy
          name: dummy
    cluster-based:
      applicationmgmt:
        join:
          cluster: clusterName
          name: workload
          namespace: namespace
        resourceType: NginxServer
      columns:
      - displayName: Accepts Handled
        source: metric
        columnItems:
          - displayName: Accepted Connections
            target: nginx-accepts
          - displayName: Handled Connections
            target: nginx-handled
      - displayName: Connections
        source: metric
        columnItems:
          - displayName: Active Connections
            target: nginx-active
          - displayName: Waiting Connections
            target: nginx-waiting
          - displayName: Writing Connections
            target: nginx-writing
          - displayName: Reading Connections
            target: nginx-reading
      - displayName: Requests
        source: metric
        columnItems:
          - displayName: Total Requests
            target: nginx-requests
